name: forcetictactoe
version: 0.0.1
description: An example with dart force
dependencies:
  stagexl: '0.8.9'
  appengine: '>=0.2.1 <0.3.0'
  force: 
    git: git://github.com/ForceUniverse/dart-force.git 
  
