name: forcetictactoe
description: An example with dart force
dependencies:
  stagexl: '0.10.3'
  stagexl_particle: any
  force: 
    git: git://github.com/ForceUniverse/dart-force.git 
  polymer: any
  core_elements: any
  paper_elements: any
  firebase: any
transformers:
- polymer:
    entry_points:
    - web/table.html
    - web/index.html
  